function(scan_and_generate_modules source_dir return_var)
    set(modules_name_r "")
    file(GLOB_RECURSE CPP_FILES "${source_dir}/*.cpp")
    foreach(cpp_file ${CPP_FILES})
        file(READ ${cpp_file} file_content)
        string(REGEX MATCH "ATOM_MODULE\\(([a-zA-Z0-9_]+)," match ${file_content})
        if(match)
            string(REGEX REPLACE "ATOM_MODULE\\(([a-zA-Z0-9_]+),.*" "\\1" module_name ${match})
            if(NOT module_name)
                message(WARNING "Found ATOM_MODULE macro in ${cpp_file} but could not extract module name.")
                continue()
            endif()
            set(modules_name_r ${module_name})
        endif()
    endforeach()
    set(${return_var} "${module_name_r}" PARENT_SCOPE)
endfunction()
