name: MinGW

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'reborn'
  pull_request:
    branches:
      - 'master'
      - 'dev'
      - 'reborn'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          mingw-w64-${{matrix.env}}-openssl
          base-devel
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-gcc
          mingw-w64-${{matrix.env}}-libnova
          mingw-w64-${{matrix.env}}-dlfcn
          mingw-w64-${{matrix.env}}-cfitsio
          mingw-w64-${{matrix.env}}-fmt
          mingw-w64-${{matrix.env}}-zlib
          mingw-w64-${{matrix.env}}-libzip
          zlib-devel

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and Test
      run: |
        ./scripts/build_win.sh
        ./scripts/test_win.sh
